In [1]:
!pip install numpy

In [2]:
import numpy as np
arr=np.array([1,2,3,4])

In [3]:
arr

array([1, 2, 3, 4])

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.size

4

In [7]:
z=np.zeros(10)

In [8]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
#one dimensional array
o=np.array([1,2,3,4])

In [11]:
o

array([1, 2, 3, 4])

In [12]:
o.ndim

1

In [13]:
o.shape

(4,)

In [15]:
#2-d array
x=np.array([[1,2,3],[4,5,6],[7,8,9],[4,9,6]])

In [16]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [4, 9, 6]])

In [17]:
x.ndim

2

In [18]:
x.shape

(4, 3)

In [19]:
#3-d array
x=x.reshape(3,2,2)

In [20]:
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 4],
        [9, 6]]])

In [21]:
x.ndim

3

In [22]:
x.shape

(3, 2, 2)

In [23]:
x.reshape(3,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 4, 9, 6]])

# Indexing

In [24]:
arr=np.array([1,2,3,4])

In [25]:
arr

array([1, 2, 3, 4])

In [26]:
arr[1]

2

In [28]:
#accesing 2d array
arr=np.array([[1,2,3,4],[6,7,8,9]])

In [29]:
arr[1]

array([6, 7, 8, 9])

In [30]:
arr[1][2]

8

In [31]:
arr[[1]]

array([[6, 7, 8, 9]])

In [32]:
arr[1,2]

8

In [33]:
#linspace
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [36]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.random.randint(0,10,10)

array([1, 5, 4, 7, 2, 5, 3, 4, 9, 8])

In [38]:
np.random.rand(3,3)

array([[0.7993374 , 0.66867796, 0.41280799],
       [0.28036213, 0.28968364, 0.61583671],
       [0.71144667, 0.2884902 , 0.33245509]])

In [41]:
np.random.rand(3,3,2)

array([[[0.475469  , 0.06722714],
        [0.45914752, 0.21495054],
        [0.82085502, 0.2706374 ]],

       [[0.60428864, 0.68302858],
        [0.25225295, 0.81652177],
        [0.33991461, 0.41449926]],

       [[0.39638406, 0.61462106],
        [0.17696866, 0.4538192 ],
        [0.60458339, 0.76516137]]])

In [42]:
arr.max()

9

In [43]:
arr.argmax() #will return the index of the max value

7

In [47]:
a=np.arange(0,11,2)  #linspace determines the number of elements but arange determine the spacing

## slicing

In [48]:
a[1:2+1]

array([2, 4])

In [51]:
a=np.array([[1,2,3],[2,3,4],[4,5,6]])

In [52]:
a[:,:]

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [79]:
a[0:1,0:3]

array([[1, 2, 3]])

In [87]:
s=a.reshape(1,3,3)

In [93]:
s[[0]][[1]]

IndexError: index 1 is out of bounds for axis 0 with size 1

In [102]:
#create an array 5*5 which should contain from 0 to 24
arr=np.random.randint(0,25,25)

In [98]:
arr

array([ 8,  8, 10, 19,  7, 14, 23,  9, 10, 22,  5, 11,  4, 13, 16,  6, 19,
        5, 11,  9, 18, 19, 10, 10,  5])

In [99]:
arr.shape

(25,)

In [104]:
arr.reshape(5,5)

array([[13, 18, 22, 19, 13],
       [ 8, 19,  1,  5, 23],
       [13, 14, 22,  3, 10],
       [ 1, 10, 17,  8, 21],
       [ 7, 21,  1,  9,  7]])

In [103]:
arr=arr.reshape(5,5)